"Show Enchanted Mob Hud" = true
# Default: 20
# Range: 0 ~ 1000
"Show Enchanted Mob Hud X Position" = 20
# Default: 50
# Range: 0 ~ 1000
"Show Enchanted Mob Hud Y Position" = 50
#Disable Poison Mob Enchant Particle. [true / false]
"Disable Poison Particle" = true
#Disable Aura Render. [true / false]
"Disable Aura Render" = false
#Enable Old Style Animation. [true / false]
"Old Style Animation" = false
