# Maximum amount of items that can be stored in a Monobank.
# Default: 8192
# Default: 8192
# Range: > 1
capacity = 8192

[lock]
	# Locking a Monobank prevents item insertion (with Hoppers, etc)
	# Default: true
	prevent_insertion = true
	# Locking a Monobank prevents item extraction (with Hoppers, etc).
	# WARNING: when disabled, other players would be able to steal items from a Monobank without entering a combination and opening it.
	# Default: true
	prevent_extraction = true
	# Players can break and pickup a Monobank that is owned by another player.
	# Default: false
	can_break_other_players_monobanks = false
	# Players can change lock in a Monobank that is owned by another player.
	# Default: false
	can_replace_other_players_locks = false

	[lock.combination]
		# Combination must be entered to unlock a Monobank.
		# Default: true
		enabled = true
		# Players can enter a combination to unlock a Monobank that is owned by someone else.
		# If disabled, only owner can open their Monobank.
		# NPC owned Monobanks are not affected by this. They can still be unlocked by everyone.
		# Default: true
		player_unlocking = true
		# Owner can unlock their Monobank without entering a combination.
		# Default: true
		skip_combination_if_owner = true
		# Any player can unlock a Monobank (player owned) without entering a combination.
		# Default: false
		skip_combination_if_not_owner = false
		# NPC-owned Monobanks (villages, etc) can be unlocked without entering a combination.
		# Default: false
		skip_combination_for_npc_owned = false

	[lock.combination_ui]
		# Show partially visible hint icon in combination slot.
		# Default: true
		hint_icon = true
		# Opacity percentage of the hint icon.
		# Default: 0.3
		# Range: 0.0 ~ 1.0
		hint_icon_opacity = 0.3
		# Chance of a letter being obfuscated in slot tooltip.
		# Default: 0.5
		# Range: 0.0 ~ 1.0
		tooltip_obfuscation_chance = 0.5

[thief]
	# Crime severity for attempting to unlock a Monobank (opening combination UI).
	# Default: LIGHT
	#Allowed Values: NONE, LIGHT, MEDIUM, HEAVY
	crime_severity_for_unlocking_attempt = "LIGHT"
	# Crime severity for unlocking a Monobank.
	# Default: MEDIUM
	#Allowed Values: NONE, LIGHT, MEDIUM, HEAVY
	crime_severity_for_unlocking = "MEDIUM"
	# Crime severity for opening a Monobank.
	# Default: HEAVY
	#Allowed Values: NONE, LIGHT, MEDIUM, HEAVY
	crime_severity_for_opening = "HEAVY"

[structures]
	# Vault buildings will generate in villages.
	# Default: true
	generate_vaults = true
	# Vault building generation weight. Larger number = more chances to generate.
	# Default: 15
	# Range: > 1
	vault_weight = 15
