#determine how often will Burneds spawn
burnedWeight = 10
#determine how often will Frostbittens spawn
frostbittenWeight = 40
#determine how often will Glacial Hunters spawn
glacialHunterWeight = 10
#determine how often will Swampies spawn
swampyWeight = 40
#determine how often will Undead Miners spawn
undeadMinerWeight = 10
#determine the max y height where Undead Miners can spawn
undeadMinerDepth = 63
#determine how often will Mummies spawn
mummyWeight = 10
#determine how often will Dead Beard spawn
deadBeardWeight = 1
#determine the chance of spawning for Immortals
immortalChance = 0.025
