# Don't change this! Version used to track needed updates.
version = 0
# Hand-delivers the sacred texts on first login. Read it—or don’t. I'm not your conscience.
enableAutoGuidebookDelivery = true
# Helpful whispers on what the heck that cucumber is for.
enableItemTooltips = true
# Little status mumbles when your co-pilot disembarks.
enableShoulderDismountMessages = true
# More stats than anyone asked for. Defaults to off—mercifully.
enableJadeHamsterDebugInfo = false
# Do we yeet the hamster? ('G' by default).
enableHamsterThrowing = true
# Gate cheek-pouch storage behind gourmet cuisine, because drama.
requireFoodMixToUnlockCheeks = true
# How often a sitting hamster gets the sudden urge to clean. It's a 1-in-X chance per tick, so lower numbers mean a higher chance for cleaning. For example, 1200 means on average, it'll clean about once a minute. 300 ≈ every 15 secs, and 5000 ≈ every 4 mins. Congratulations— now you know enough to be dangerous.
cleaningChanceDenominator = 1200
# Time-out after using your living projectile. (20 ticks = 1 s)
hamsterThrowCooldown = 2400
# When the sugar rush ends, force a breather. (20 ticks = 1 s)
steamedGreenBeansBuffCooldown = 6000
# Adjusts hamster spawn frequency. Higher = more chaos. 1 = blissful silence.
spawnWeight = 30
# Maximum hamsters per spawn group. Because sometimes one just isn't cute enough.
maxGroupSize = 1
# Taming difficulty (1 in X chance). Higher = more cucumbers sacrificed to fuzzy freeloaders.
tamingChanceDenominator = 3
# Hamsters need their space. (20 ticks = 1 s)
breedingCooldownTicks = 6000
# May save your inventory. Or your ears.
enableShoulderCreeperDetection = true
# Adjust paranoia levels.
shoulderCreeperDetectionRadius = 16.0
# Because who doesn’t enjoy unsolicited financial advice from a rodent?
enableShoulderDiamondDetection = true
# How close you need to be before the squeak says \"bling.\"
shoulderDiamondDetectionRadius = 10.0
# Permit hamsters to embark on solo get-rich-quick schemes?
enableIndependentDiamondSeeking = true
# How far a hamster scans once it’s decided to play prospector.
diamondSeekRadius = 10
# The probability (0.0 to 1.0) that a hamster will seek gold instead of diamond, if both are available. At 0.5, it's a coin toss. At 1.0, it's guaranteed hamster sulking.
goldMistakeChance = 0.33
# Force a cool-down after striking it rich. Off by default, since this can't happen again anyway without another mount/dismount on the shoulder.
enableIndependentDiamondSeekCooldown = false
# Cooldown before your hamster can go on another treasure hunt. (20 ticks = 1 s)
independentOreSeekCooldownTicks = 2400
# How close a hostile mob can get before a hamster wakes up from it's power nap.
tamedSleepThreatDetectionRadiusBlocks = 8
# Night-owl hamsters? Your choice.
requireDaytimeForTamedSleep = true
# Minimum seconds before a sitting hamster gets sleepy.
tamedQuiescentSitMinSeconds = 120
# Maximum seconds before the inevitable deep snooze.
tamedQuiescentSitMaxSeconds = 180
# Tamed hamster melee damage. Mostly for show, let's be honest.
meleeDamage = 2.0
# Damage dealt by thrown hamster. Surprisingly effective against Creepers. How convenient.
hamsterThrowDamage = 30.0
# Healing amount from Hamster Food Mix. The good stuff.
hamsterFoodMixHealing = 4.0
# Healing from basic seeds/crops. Better than nothing… probably.
standardFoodHealing = 2.0
# Steamed beans: power that fades faster than your attention span.
greenBeanBuffDuration = 3600
# Because someone has to go fast.
greenBeanBuffAmplifierSpeed = 1
# Slightly mightier nibbles.
greenBeanBuffAmplifierStrength = 1
# Extra fluff padding for those daring dives.
greenBeanBuffAmplifierAbsorption = 1
# Heals minor paper-cuts (and fragile egos).
greenBeanBuffAmplifierRegen = 0
# Higher = slower, lower = faster. Makes perfect sense.
sunflowerRegrowthModifier = 1.0
# Higher = slower, lower = faster. Still makes perfect sense.
wildBushRegrowthModifier = 1.0
# 1 in X chunks. Low numbers may cause shrub spam.
wildGreenBeanBushRarity = 24
# 1 in X chunks. Low numbers may cause shrub spam.
wildCucumberBushRarity = 24